# Generated by Django 2.2.3 on 2019-10-30 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notafiscal', to='catalogs.Empresa'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
